# Chirpy 블로그 설정 (_config.yml)
title: Tanukimchi Blog
description: "파이썬, 머신러닝, 일본 생활"
baseurl: "" # 루트 도메인에서 실행할 때는 빈 문자열
url: "https://jjm19.github.io" # 사용자 GitHub 주소

# 사이트 소유자 정보
author:
  name: Tanukimchi
  url: https://jjm19.github.io/Tanukimchi_blog/

# 소셜 미디어 및 SEO
social:
  name: Tanukimchi Blog
  links:
    - https://github.com/jjm19
    - https://www.kaggle.com/your_kaggle_Tanukimchi

lang: en

# 빌드 설정
theme: jekyll-theme-chirpy
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

markdown: kramdown
highlighter: rouge

# 블로그 옵션들
paginate: 10
paginate_path: "/page:num"
toc: true
toc_sticky: true

# 시간 설정
timezone: Asia/Tokyo

# 댓글, GA, 기타 설정은 이후에 추가 가능

# 배포 관련 (GitHub Pages 사용 시)
deploy:
  branch: gh-pages
  method: git
